[package]
name = "sensu-plugins-rust-loader"
version = "0.1.0"
authors = ["metalels <metalels86@gmail.com>"]

[[bin]]
name = "metrics-rust-loader"
path = "src/bin/metrics-rust-loader.rs"

[dependencies]
"yaml-rust"   = "*"
"getopts"     = "*"
